### ISSUE TITLE
Crash when pressing the back button

### ISSUE THREAD

**Issue by opk12** [mcastillof/FakeTraveler#48]
Launch the app, choose location, press `Apply`, press the phone's Back button at the right. There is the message `Fake traveler was closed. Mock location stopped`, then there is Android's pop-up notification that Fake Traveler crashed or keeps crashing.

**Information:**
 - OS: Android 7
 - FakeTraveler version: 1.7 from F-droid

**Additional context**
This does not happen if `Apply` was not pressed, or if `Stop` was pressed.

```
java.lang.RuntimeException: Unable to destroy activity {cl.coders.faketraveler/cl.coders.faketraveler.MainActivity}: java.lang.IllegalArgumentException: Provider "network" unknown
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4697)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1720)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.IllegalArgumentException: Provider "network" unknown
	at android.os.Parcel.readException(Parcel.java:1716)
	at android.os.Parcel.readException(Parcel.java:1662)
	at android.location.ILocationManager$Stub$Proxy.removeTestProvider(ILocationManager.java:1212)
	at android.location.LocationManager.removeTestProvider(LocationManager.java:1254)
	at cl.coders.faketraveler.MockLocationProvider.shutdown(MockLocationProvider.java:79)
	at cl.coders.faketraveler.MainActivity.stopMockingLocation(MainActivity.java:371)
	at cl.coders.faketraveler.MainActivity.onDestroy(MainActivity.java:188)
	at android.app.Activity.performDestroy(Activity.java:7255)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4657)
	... 9 more

```

**Comment by ThexXTURBOXx** [comment]
Seems to be outdated/stale/for an old version
