### ISSUE TITLE
App crash right after applying location.

### ISSUE THREAD

**Issue by shom13** [mcastillof/FakeTraveler#62]
**Describe the bug**
App crashes right after applying selected location

**Information:**
 - OS: Android 12
 - FakeTraveler version: 1.9.1

**To Reproduce**
After selecting desired location, click on apply and the app crashes.

**Comment by Albuslund** [comment]
The same problem happened to me as well.

Android 13, One UI 5.1

The most recent version of the app.

Cheers everyone, and thank you for all your invaluable efforts!

**Comment by adam-leitgeb** [comment]
Same problem on Android 13 (Graphene OS). Crash after applying fake location. 

Stack trace:

```
type: crash
osVersion: google/panther/panther:13/TQ3A.230605.012/2023061402:user/release-keys
package: cl.coders.faketraveler:9
process: cl.coders.faketraveler
processUptime: 7396 + 310 ms

java.lang.IllegalStateException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3029)
	at android.os.Parcel.createException(Parcel.java:3005)
	at android.os.Parcel.readException(Parcel.java:2981)
	at android.os.Parcel.readException(Parcel.java:2923)
	at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2169)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2131)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2106)
	at android.location.LocationManager.addTestProvider(LocationManager.java:2080)
	at cl.coders.faketraveler.MockLocationProvider.<init>(MockLocationProvider.java:28)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:257)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
	at com.android.internal.util.Preconditions.checkState(Preconditions.java:200)
	at com.android.server.location.LocationManagerService.addLocationProviderManager(LocationManagerService.java:350)
	at com.android.server.location.LocationManagerService.getOrAddLocationProviderManager(LocationManagerService.java:342)
	at com.android.server.location.LocationManagerService.addTestProvider(LocationManagerService.java:1319)


```

**Comment by imongithubnow** [comment]
same here, only when I set "how many time you want to mock the location?" to zero.

redmi note 8 rooted with crDroid 9.7 (A13)

time: 1690019752784
msg: java.lang.IllegalArgumentException: cl.coders.faketraveler: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
stacktrace: java.lang.IllegalArgumentException: cl.coders.faketraveler: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
	at cl.coders.faketraveler.MainActivity.setAlarm(MainActivity.java:318)
	at cl.coders.faketraveler.MainActivity.applyLocation(MainActivity.java:270)
	at cl.coders.faketraveler.MainActivity$1.onClick(MainActivity.java:81)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29487)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7930)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

**Comment by 424778940z** [comment]
same issue here, any fix?

**Comment by ascshank** [comment]
Also have problem in Android 9.

**Comment by Deleted-Account404** [comment]
Did anybody come thru with the fix to this? Obviously it's a common issue. Is there a common fix? App crashes right after applying location. I've got to find a PC. TCL throwaway
